// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFdcFS9_aWhylf4nYK4M8peZyRZwcy1y8',
    appId: '1:146805890261:web:70d4c145517f0b4871565c',
    messagingSenderId: '146805890261',
    projectId: 'bookstore-app-9d8ca',
    authDomain: 'bookstore-app-9d8ca.firebaseapp.com',
    storageBucket: 'bookstore-app-9d8ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDWqECb0CP2m7RsmwifdYgIEephTrNQd4',
    appId: '1:146805890261:android:da2dd61edfb16cdd71565c',
    messagingSenderId: '146805890261',
    projectId: 'bookstore-app-9d8ca',
    storageBucket: 'bookstore-app-9d8ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQnEFbpUii48itjyMuUCOJPSXLBROUPl8',
    appId: '1:146805890261:ios:3d7202f8d637b29271565c',
    messagingSenderId: '146805890261',
    projectId: 'bookstore-app-9d8ca',
    storageBucket: 'bookstore-app-9d8ca.firebasestorage.app',
    iosBundleId: 'com.example.bookstoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQnEFbpUii48itjyMuUCOJPSXLBROUPl8',
    appId: '1:146805890261:ios:3d7202f8d637b29271565c',
    messagingSenderId: '146805890261',
    projectId: 'bookstore-app-9d8ca',
    storageBucket: 'bookstore-app-9d8ca.firebasestorage.app',
    iosBundleId: 'com.example.bookstoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFdcFS9_aWhylf4nYK4M8peZyRZwcy1y8',
    appId: '1:146805890261:web:5dd8da1c238acd9771565c',
    messagingSenderId: '146805890261',
    projectId: 'bookstore-app-9d8ca',
    authDomain: 'bookstore-app-9d8ca.firebaseapp.com',
    storageBucket: 'bookstore-app-9d8ca.firebasestorage.app',
  );
}
